#!Groovy

pipeline {
    agent {
        label 'master'
    }
    options {
        timestamps()
    }
    stages {
        stage("Build") {
            steps {
                sh 'sudo mkdir /home/rinmamar/Jenkins' 
            }
        }
    }
}
